name: Android CI
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
    
jobs:
  build: 
    runs-on: ubuntu-latest
    env:
      working-directory: ./Application/Wits_Academy
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
      - name: Setup JDK
        uses: actions/setup-java@v3.9.0
        with:
          java-version: 11
        env:
          working-directory: ./Application/Wits_Academy
      - name: Build with Gradle
        run: ./Application/Wits_Academy/gradlew build
      - name: Upload Apk
        uses: actions/upload-artifact@v3.1.2
        with:
          name: wits_academy
          path: app/build/outputs/apk/debug/wits_academy
        
