name: Android CI
on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
    
jobs:
  build: 
    runs-on: ubuntu-latest
    env:
      working-directory: ./Application/Wits_Academy
    steps:
      - name: Checkout
        uses: actions/checkout@v2.7.0
      - name: Setup JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload Apk
        uses: actions/upload-artifact@v3.1.2
        with:
          name: wits_academy
          path: app/build/outputs/apk/debug/wits_academy
        
